"use strict";
class Rules{constructor(n){this.n=n;this.k=n;this.counts=n===3?[2,2,2]:[4,3,3];this.lines=[];for(let r=0;r<n;r++)this.lines.push(Array.from({length:n},(_,c)=>r*n+c));for(let c=0;c<n;c++)this.lines.push(Array.from({length:n},(_,r)=>r*n+c));this.lines.push(Array.from({length:n},(_,i)=>i*n+i));this.lines.push(Array.from({length:n},(_,i)=>i*n+n-1-i))}}
class State{
 constructor(r,board=null,reserves=null,turn=0){this.rules=r;this.board=board||Array.from({length:r.n*r.n},()=>[]);this.reserves=reserves||[[...r.counts],[...r.counts]];this.turn=turn}
 top(i){const s=this.board[i];return s[s.length-1]||null}
 winners(){const out=[];for(const line of this.rules.lines){const first=this.top(line[0]);if(!first)continue;let ok=true;for(let i=1;i<line.length;i++){const p=this.top(line[i]);if(!p||p.player!==first.player){ok=false;break}}if(ok&&!out.some(x=>x.player===first.player))out.push({player:first.player,line})}return out}
 legal(m){if(!Number.isInteger(m.dst)||m.dst<0||m.dst>=this.board.length||m.size<1||m.size>3)return false;const target=this.top(m.dst);if(target&&m.size<=target.size)return false;if(m.src===null)return this.reserves[this.turn][m.size-1]>0;if(!Number.isInteger(m.src)||m.src<0||m.src>=this.board.length||m.src===m.dst)return false;const p=this.top(m.src);return !!p&&p.player===this.turn&&p.size===m.size}
 apply(m){const b=this.board.slice(),r=[this.reserves[0],this.reserves[1]];b[m.dst]=b[m.dst].slice();if(m.src===null){r[this.turn]=this.reserves[this.turn].slice();r[this.turn][m.size-1]--;b[m.dst].push({player:this.turn,size:m.size})}else{b[m.src]=b[m.src].slice();b[m.dst].push(b[m.src].pop())}return new State(this.rules,b,r,1-this.turn)}
 moves(){const a=[],n=this.board.length;for(let z=1;z<=3;z++)if(this.reserves[this.turn][z-1]>0)for(let d=0;d<n;d++){const m={src:null,dst:d,size:z};if(this.legal(m))a.push(m)}for(let s=0;s<n;s++){const p=this.top(s);if(p?.player===this.turn)for(let d=0;d<n;d++){const m={src:s,dst:d,size:p.size};if(this.legal(m))a.push(m)}}return a}
}
class AI{
 static choose(s,diff,limit,divine=false){const start=performance.now(),deadline=start+limit,root=s.turn;let moves=s.moves(),nodes=0;if(!moves.length)return{move:null,depth:0,nodes,score:s.turn===0?-100000:100000,elapsed:0};for(const m of moves){if(performance.now()>=deadline)break;const wins=s.apply(m).winners();if(wins.length===1&&wins[0].player===root)return{move:m,depth:1,nodes,score:root===0?100000:-100000,elapsed:performance.now()-start}}if(diff==='easy'&&!divine)return{move:moves[Math.floor(Math.random()*moves.length)],depth:1,nodes,score:this.eval(s,0,false),elapsed:performance.now()-start};const safe=[];for(const m of moves){if(performance.now()>=deadline)break;const next=s.apply(m);let loses=false;for(const reply of next.moves()){if(performance.now()>=deadline)break;nodes++;const wins=next.apply(reply).winners();if(wins.length===1&&wins[0].player!==root){loses=true;break}}if(!loses)safe.push(m)}if(safe.length)moves=safe;moves=this.order(s,moves,divine);const maxDepth=divine?9:({medium:2,hard:3,expert:6}[diff]||2),tt=new Map(),ttMax=divine?150000:60000;let best=moves[0],completed=0,previous='',stable=0,finalScore=this.eval(s,root,divine);for(let depth=1;depth<=maxDepth;depth++){if(performance.now()>=deadline)break;let local=null,score=-Infinity,second=-Infinity;for(const m of moves){if(performance.now()>=deadline)break;const r=this.search(s.apply(m),depth-1,-Infinity,Infinity,root,deadline,tt,ttMax,divine);nodes+=r.nodes;if(r.score>score){second=score;score=r.score;local=m}else if(r.score>second)second=r.score}if(!local)break;best=local;completed=depth;finalScore=score;moves=[best,...moves.filter(m=>!this.same(m,best))];const key=this.moveKey(best);stable=key===previous?stable+1:1;previous=key;if(score>=90000)break;if(!divine&&stable>=3&&score-second>=120)break;if(divine&&stable>=5&&depth>=7&&score-second>=240)break}return{move:best,depth:completed,nodes,score:finalScore,elapsed:performance.now()-start}}
 static search(s,depth,a,b,root,deadline,tt,ttMax,divine){let nodes=1;if(performance.now()>=deadline)return{score:this.eval(s,root,divine),nodes};const a0=a,b0=b,key=this.hash(s,root),cached=tt.get(key);if(cached&&cached.depth>=depth){if(cached.flag==='EXACT')return{score:cached.score,nodes};if(cached.flag==='LOWER')a=Math.max(a,cached.score);else if(cached.flag==='UPPER')b=Math.min(b,cached.score);if(a>=b)return{score:cached.score,nodes}}const wins=s.winners();if(wins.length>=2)return{score:0,nodes};if(wins.some(w=>w.player===root))return{score:100000+depth*20,nodes};if(wins.some(w=>w.player!==root))return{score:-100000-depth*20,nodes};if(depth<=0){const score=this.eval(s,root,divine);this.store(tt,key,{depth,score,flag:'EXACT',bestMove:null},ttMax);return{score,nodes}}let moves=s.moves();if(!moves.length)return{score:s.turn===root?-100000-depth:100000+depth,nodes};moves=cached?.bestMove?[cached.bestMove,...moves.filter(m=>!this.same(m,cached.bestMove))]:this.order(s,moves,divine);const max=s.turn===root;let value=max?-Infinity:Infinity,best=moves[0];for(const m of moves){if(performance.now()>=deadline)break;const r=this.search(s.apply(m),depth-1,a,b,root,deadline,tt,ttMax,divine);nodes+=r.nodes;if(max){if(r.score>value){value=r.score;best=m}a=Math.max(a,value)}else{if(r.score<value){value=r.score;best=m}b=Math.min(b,value)}if(a>=b)break}if(!Number.isFinite(value))value=this.eval(s,root,divine);const flag=value<=a0?'UPPER':value>=b0?'LOWER':'EXACT';this.store(tt,key,{depth,score:value,flag,bestMove:best},ttMax);return{score:value,nodes}}
 static eval(s,root,divine){let score=0,n=s.rules.n;for(const line of s.rules.lines){let mine=0,opp=0,ms=0,os=0;for(const q of line){const p=s.top(q);if(!p)continue;if(p.player===root){mine++;ms+=p.size}else{opp++;os+=p.size}}if(mine&&!opp)score+=(divine?10:8)**mine+ms*(divine?5:3);if(opp&&!mine)score-=(divine?11:9)**opp+os*(divine?6:3);if(mine===n-1&&!opp)score+=divine?1500:900;if(opp===n-1&&!mine)score-=divine?1800:1100}const centers=n===3?[4]:[5,6,9,10];for(const q of centers){const p=s.top(q);if(p)score+=(p.player===root?1:-1)*((divine?18:12)+p.size*(divine?4:2))}if(divine){for(let i=0;i<s.board.length;i++){const stack=s.board[i],top=stack[stack.length-1];if(!top)continue;score+=(top.player===root?1:-1)*(3+stack.length*2);if(stack.length>1){const hidden=stack[stack.length-2];if(hidden.player===root&&top.player!==root)score-=7;if(hidden.player!==root&&top.player===root)score+=7}}const reserveValue=[2,5,11];for(let z=0;z<3;z++)score+=(s.reserves[root][z]-s.reserves[1-root][z])*reserveValue[z];const rootState=s.turn===root?s:new State(s.rules,s.board,s.reserves,root);const oppState=s.turn===1-root?s:new State(s.rules,s.board,s.reserves,1-root);score+=(rootState.moves().length-oppState.moves().length)*0.8}return score}
 static order(s,moves,divine){const centers=s.rules.n===3?[4]:[5,6,9,10];return moves.map(m=>({m,v:this.priority(s,m,centers,divine)})).sort((x,y)=>y.v-x.v).map(x=>x.m)}
 static priority(s,m,centers,divine){const target=s.top(m.dst);let v=m.size*4+(centers.includes(m.dst)?15:0)+(target?20:0);if(target&&target.player!==s.turn)v+=divine?18:10;if(divine&&m.src!==null)v+=4;const wins=s.apply(m).winners();if(wins.length===1&&wins[0].player===s.turn)v+=100000;return v}
 static hash(s,root){let k=`${root}|${s.turn}|${s.reserves[0].join('')}${s.reserves[1].join('')}|`;for(const stack of s.board){let cell=0,mul=1;for(const p of stack){cell+=(1+p.player*3+p.size)*mul;mul*=8}k+=cell+','}return k}
 static store(tt,key,value,max){if(!tt.has(key)||value.depth>=tt.get(key).depth)tt.set(key,value);if(tt.size>max)tt.delete(tt.keys().next().value)}
 static same(a,b){return!!a&&!!b&&a.src===b.src&&a.dst===b.dst&&a.size===b.size}
 static moveKey(m){return`${m.src??'r'}:${m.dst}:${m.size}`}
}
function restore(data){const r=new Rules(data.rules.n);r.lines=data.rules.lines;r.counts=data.rules.counts;return new State(r,data.board.map(s=>s.map(p=>({...p}))),data.reserves.map(x=>[...x]),data.turn)}
self.addEventListener('message',event=>{const m=event.data;if(m?.type!=='SEARCH')return;try{const state=restore(m.state),divine=m.purpose==='GOD'||m.purpose==='ANALYZE';const result=AI.choose(state,m.difficulty,m.timeLimit,divine);if(m.purpose==='ANALYZE'&&state.turn===1)result.score=-result.score;self.postMessage({type:'RESULT',jobId:m.jobId,purpose:m.purpose,...result})}catch(error){self.postMessage({type:'ERROR',jobId:m.jobId,purpose:m.purpose,message:error instanceof Error?error.message:String(error)})}});
