"use strict";
class Rules{constructor(data){this.n=data.n;this.lines=data.lines;this.counts=data.counts}}
class State{
 constructor(rules,board,reserves,turn){this.rules=rules;this.board=board;this.reserves=reserves;this.turn=turn}
 top(i){const s=this.board[i];return s[s.length-1]||null}
 winners(){const out=[];for(const line of this.rules.lines){const first=this.top(line[0]);if(!first)continue;let ok=true;for(let i=1;i<line.length;i++){const p=this.top(line[i]);if(!p||p.player!==first.player){ok=false;break}}if(ok&&!out.some(w=>w.player===first.player))out.push({player:first.player,line})}return out}
 legal(m){if(!Number.isInteger(m.dst)||m.dst<0||m.dst>=this.board.length||m.size<1||m.size>3)return false;const target=this.top(m.dst);if(target&&m.size<=target.size)return false;if(m.src===null)return this.reserves[this.turn][m.size-1]>0;if(!Number.isInteger(m.src)||m.src<0||m.src>=this.board.length||m.src===m.dst)return false;const p=this.top(m.src);return !!p&&p.player===this.turn&&p.size===m.size}
 apply(m){const b=this.board.slice(),r=[this.reserves[0],this.reserves[1]];b[m.dst]=b[m.dst].slice();if(m.src===null){r[this.turn]=this.reserves[this.turn].slice();r[this.turn][m.size-1]--;b[m.dst].push({player:this.turn,size:m.size})}else{b[m.src]=b[m.src].slice();b[m.dst].push(b[m.src].pop())}return new State(this.rules,b,r,1-this.turn)}
 moves(){const a=[],n=this.board.length;for(let z=1;z<=3;z++)if(this.reserves[this.turn][z-1]>0)for(let d=0;d<n;d++){const m={src:null,dst:d,size:z};if(this.legal(m))a.push(m)}for(let src=0;src<n;src++){const p=this.top(src);if(p?.player===this.turn)for(let d=0;d<n;d++){const m={src,dst:d,size:p.size};if(this.legal(m))a.push(m)}}return a}
}
class AI{
 static choose(s,diff,limit){const start=performance.now(),deadline=start+limit,root=s.turn;let moves=s.moves(),nodes=0;if(!moves.length)return{move:null,depth:0,nodes,elapsed:0};for(const m of moves){if(performance.now()>=deadline)break;if(s.apply(m).winners().some(w=>w.player===root))return{move:m,depth:1,nodes,elapsed:performance.now()-start}}if(diff==='easy')return{move:moves[Math.floor(Math.random()*moves.length)],depth:1,nodes,elapsed:performance.now()-start};const safe=[];for(const m of moves){if(performance.now()>=deadline)break;const next=s.apply(m);let loses=false;for(const reply of next.moves()){if(performance.now()>=deadline)break;nodes++;if(next.apply(reply).winners().some(w=>w.player!==root)){loses=true;break}}if(!loses)safe.push(m)}if(safe.length)moves=safe;moves=this.order(s,moves);const maxDepth={medium:2,hard:3,expert:6}[diff]||2,tt=new Map();let best=moves[0],completed=0,previous='',stable=0;for(let depth=1;depth<=maxDepth;depth++){if(performance.now()>=deadline)break;let local=null,score=-Infinity,second=-Infinity;for(const m of moves){if(performance.now()>=deadline)break;const result=this.search(s.apply(m),depth-1,-Infinity,Infinity,root,deadline,tt);nodes+=result.nodes;if(result.score>score){second=score;score=result.score;local=m}else if(result.score>second)second=result.score}if(!local)break;best=local;completed=depth;moves=[best,...moves.filter(m=>!this.same(m,best))];const key=this.moveKey(best);stable=key===previous?stable+1:1;previous=key;if(score>=90000||(stable>=3&&score-second>=120))break}return{move:best,depth:completed,nodes,elapsed:performance.now()-start}}
 static search(s,depth,a,b,root,deadline,tt){let nodes=1;if(performance.now()>=deadline)return{score:this.eval(s,root),nodes};const a0=a,b0=b,key=this.hash(s,root),cached=tt.get(key);if(cached&&cached.depth>=depth){if(cached.flag==='EXACT')return{score:cached.score,nodes};if(cached.flag==='LOWER')a=Math.max(a,cached.score);else if(cached.flag==='UPPER')b=Math.min(b,cached.score);if(a>=b)return{score:cached.score,nodes}}const wins=s.winners();if(wins.length>=2)return{score:0,nodes};if(wins.some(w=>w.player===root))return{score:100000+depth,nodes};if(wins.some(w=>w.player!==root))return{score:-100000-depth,nodes};if(depth<=0){const score=this.eval(s,root);this.store(tt,key,{depth,score,flag:'EXACT',bestMove:null});return{score,nodes}}let moves=s.moves();if(!moves.length)return{score:s.turn===root?-100000-depth:100000+depth,nodes};moves=cached?.bestMove?[cached.bestMove,...moves.filter(m=>!this.same(m,cached.bestMove))]:this.order(s,moves);const max=s.turn===root;let value=max?-Infinity:Infinity,best=moves[0];for(const m of moves){if(performance.now()>=deadline)break;const r=this.search(s.apply(m),depth-1,a,b,root,deadline,tt);nodes+=r.nodes;if(max){if(r.score>value){value=r.score;best=m}a=Math.max(a,value)}else{if(r.score<value){value=r.score;best=m}b=Math.min(b,value)}if(a>=b)break}if(!Number.isFinite(value))value=this.eval(s,root);const flag=value<=a0?'UPPER':value>=b0?'LOWER':'EXACT';this.store(tt,key,{depth,score:value,flag,bestMove:best});return{score:value,nodes}}
 static eval(s,root){let score=0,n=s.rules.n;for(const line of s.rules.lines){let mine=0,opp=0,ms=0,os=0;for(const q of line){const p=s.top(q);if(!p)continue;if(p.player===root){mine++;ms+=p.size}else{opp++;os+=p.size}}if(mine&&!opp)score+=8**mine+ms*3;if(opp&&!mine)score-=9**opp+os*3;if(mine===n-1&&!opp)score+=900;if(opp===n-1&&!mine)score-=1100}for(const q of(n===3?[4]:[5,6,9,10])){const p=s.top(q);if(p)score+=(p.player===root?1:-1)*(12+p.size*2)}return score}
 static order(s,moves){const centers=s.rules.n===3?[4]:[5,6,9,10];return moves.map(m=>({m,v:m.size*4+(centers.includes(m.dst)?15:0)+(s.top(m.dst)?20:0)})).sort((x,y)=>y.v-x.v).map(x=>x.m)}
 static hash(s,root){let k=`${root}|${s.turn}|${s.reserves[0].join('')}${s.reserves[1].join('')}|`;for(const stack of s.board){let cell=0,mul=1;for(const p of stack){cell+=(1+p.player*3+p.size)*mul;mul*=8}k+=cell+','}return k}
 static store(tt,key,value){if(!tt.has(key)||value.depth>=tt.get(key).depth)tt.set(key,value);if(tt.size>60000)tt.delete(tt.keys().next().value)}
 static same(a,b){return!!a&&!!b&&a.src===b.src&&a.dst===b.dst&&a.size===b.size}
 static moveKey(m){return`${m.src??'r'}:${m.dst}:${m.size}`}
}
function restore(data){return new State(new Rules(data.rules),data.board.map(s=>s.map(p=>({...p}))),[[...data.reserves[0]],[...data.reserves[1]]],data.turn)}
self.addEventListener('message',event=>{const m=event.data;if(m?.type!=='SEARCH')return;try{const result=AI.choose(restore(m.state),m.difficulty,m.timeLimit);self.postMessage({type:'RESULT',jobId:m.jobId,purpose:m.purpose,...result})}catch(error){self.postMessage({type:'ERROR',jobId:m.jobId,purpose:m.purpose,message:error instanceof Error?error.message:String(error)})}});
